# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/olives/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/olives

# Inherit fragments
$(call inherit-product, vendor/xiaomi/olives/olives-vendor-acdb.mk)
