# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/olives/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/olives

# Inherit fragments
$(call inherit-product, vendor/xiaomi/olives/olives-vendor-acdb.mk)
$(call inherit-product, vendor/xiaomi/olives/olives-vendor-fingerprint.mk)
$(call inherit-product, vendor/xiaomi/olives/olives-vendor-firmware.mk)
$(call inherit-product, vendor/xiaomi/olives/olives-vendor-ir.mk)

$(call inherit-product-if-exists, vendor/xiaomi/olives-camera/olives-camera-vendor.mk)
